kind: ConfigMap
apiVersion: v1
metadata:
  name: organization
data:
  logging.pattern.console: "%d{HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  spring.cloud.kubernetes.discovery.all-namespaces: "true"
  spring.data.mongodb.database: "admin"
  spring.data.mongodb.authentication-database: "admin"
  spring.data.mongodb.host: "mongodb.default"
  management.endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS