apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi